server:
  port: 8080
spring:
  application:
    name: "ms_login_bancolombia"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  ecs:
    logs:
      request:
        replacement: ""
        patterns: ""
        delimiter: ""
        fields: ""
        allow-headers: ""
        excluded-paths: "/actuator"
        show: false
      response:
        replacement: ""
        delimiter: ""
        fields: ""
        patterns: ""
        show: false
      sampling:
        rules20XJson: ""
        rules40XJson: ""
      sensitive-rules:
        sensitive-data: ""
